# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/12087"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    groups:
      opentelemetry-instrumentation:
        patterns:
          - "opentelemetry-instrumentation*"
      python-minor-versions:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
          
  - package-ecosystem: "uv"
    directory: "12196"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 16
    rebase-strategy: "disabled"
    pull-request-branch-name:
      # so it's compatible with docker tags
      separator: "-"
    
  - package-ecosystem: "uv"
    directory: "12788"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "uv"
    directory: "13707"
    versioning-strategy: increase-if-necessary
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/13426"
    schedule:
      interval: "weekly"
    groups:
      security-dependencies:
        applies-to: "security-updates"
        patterns:
          - "*"
      production-dependencies:
        exclude-patterns:
          - "beautifulsoup4"
          - "ipykernel"
          - "lxml"
          - "pandas-ods-reader"
          - "playwright*"
          - "pyflakes"
          - "pytest*"
          - "ruff"
          - "tox*"
      development-dependencies:
        patterns:
          - "beautifulsoup4"
          - "ipykernel"
          - "lxml"
          - "pandas-ods-reader"
          - "playwright*"
          - "pyflakes"
          - "pytest*"
          - "ruff"
          - "tox*"
  - package-ecosystem: uv
    schedule:
      interval: weekly
      day: "thursday"
      time: "14:00"
    commit-message:
      prefix: '(test-repo) '
    insecure-external-code-execution: allow
    directory: /13773
    open-pull-requests-limit: 1
    patterns: ["*"]
    groups:
      all-updates:
        patterns: ["*"]

  - package-ecosystem: uv
    schedule: 
      interval: daily
    directory: /3655848831

    
