# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/12087"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    groups:
      opentelemetry-instrumentation:
        patterns:
          - "opentelemetry-instrumentation*"
      python-minor-versions:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
          
  - package-ecosystem: "uv"
    directory: "12196"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "uv"
    directory: "12788"
    schedule:
      interval: "weekly"
